### ISSUE TITLE
Use stackable headers & remove proto zone

### ISSUE THREAD

**Issue by AllWize** [AllWize/AllWizeK1-hardware#12]
Even if the K1 is forced to be a top-shield, it is interesting to mount stackable headers (with female holes on top) so there is no need to solder the extra rows of headers to have easy access to other GPIOs.

**Comment by xoseperez** [comment]
Done with Rev.PB

**Comment by xoseperez** [comment]
BTW, see https://store.arduino.cc/headers-strip-14-ways-arduino-mkr1000-printed
