### ISSUE TITLE
Add uFL footprint

### ISSUE THREAD

**Issue by AllWize** [AllWize/AllWizeK1-hardware#15]
The main benefit is that we will not be limited to be a top shield. Right now the issue is the lack of (good) 90 degrees antenna.

It's OK if it's to factory-ready that would require a solder-jumper change.
Or even better, place the uFL footprint in the path, not mounted, and a resistor bridge that should be removed before placing the uFL, the same pad of the resistor would double and uFL live.

**Comment by xoseperez** [comment]
Done with Rev.PB
