### ISSUE TITLE
Use hardware serial by default

### ISSUE THREAD

**Issue by AllWize** [AllWize/AllWizeK1-hardware#16]
We think it will ease the use of the board to remove the jumper selector and set it to hardware serial by default with solder pads to allow the user to cut and solder a different option. Very much like this board:

https://github.com/ttn-liv/LoRaWANshield

Options: 0 (default for RX),1 (default for TX), 2, 3, 4, 8 and 9.

**Comment by xoseperez** [comment]
Done with Rev.PB
