### ISSUE TITLE
[Allwize] Missing info in the silkscreen

### ISSUE THREAD

**Issue by AllWize** [AllWize/AllWizeK1-hardware#5]
I'm missing proper information in the silkscreen for these designators

- J3 (RC programming header) - RC
- J4 (serial selector) - UART
- J6 (sensor reference) - SNS_PWR
- J7 (I2C grove connector) - I2C
- J8 (Analog grove connector: A0, A1) - ANA
- J9 (Digital grove connector: D5, D6) - DIO
- J12 (ICSP) - ICSP
- J13 (module flashing, not sure this is needed since it's still a testing feature)

![p1240905s](https://user-images.githubusercontent.com/38039350/39692092-1ab1491a-51e0-11e8-988d-93682840731f.jpg)

**Comment by xoseperez** [comment]
Fixed with RevPB
